# Generated by Django 5.0.6 on 2024-05-15 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vacancy_currency_vacancy_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(max_length=5, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата'),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proffesion', models.CharField(max_length=50, verbose_name='Проффесия')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='')),
                ('currency', models.CharField(max_length=5, null=True, verbose_name='Валюта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
